// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = '1ea9605fc00758f2b7fbd569946df3c8721c611cc182ba007fb489ddc788be8a' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 59253 as const;
